#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'equalStacks' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY h1
#  2. INTEGER_ARRAY h2
#  3. INTEGER_ARRAY h3
#

def equalStacks(h1, h2, h3):
    # Write your code here
    
    h1sum=0
    for i in h1:
        h1sum+=i
        
    h2sum=0  
    for i in h2:
        h2sum+=i
    h3sum=0
    
    for i in h3:
        h3sum+=i
    
    if h1sum == h2sum and  h2sum==h3sum:
        return h1sum
    
    h1.reverse()
    h2.reverse()
    h3.reverse()

    while not(h1sum== h2sum==h3sum):
        ma = max(h1sum, h2sum, h3sum)
        if h1sum == ma:
            h1sum -= h1.pop()
        elif h2sum == ma:
            h2sum -= h2.pop()
        elif h3sum == ma:
            h3sum -= h3.pop()
    return h1sum     

 

    
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n1 = int(first_multiple_input[0])

    n2 = int(first_multiple_input[1])

    n3 = int(first_multiple_input[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result) + '\n')

    fptr.close()
