#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    temp = arr[n-1]
    j = n - 2  
    while j>=0:
        if temp<arr[j]:
            arr[j+1] = arr[j]
            print(*arr, sep=" ")
        else:
            
            arr[j+1]=temp
            print(*arr, sep=" ")
            return
        
        if j == 0:    
            arr[0]=temp
            print(*arr, sep=" ")
            return
        j-=1

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
    
    
    
    
    
    
    
    
    
    
    
    
    #  insertion sorting  
# List = [9,8,7,7,4,5,6,1,2,3]
# for i in range(1,len(List)):
#     key = List[i]
#     j=i-1
#     while j>=0 and key < List[j]:    
#         List[j + 1] = List[j]
#         j-=1   
#     List[j + 1] = key 
# print(List)
    
